##################
# Run Parameters #
##################


### STICK TO YOUR SYSTEM'S CPU:RAM RATIO FOR THESE
# this will be overwritten by the Snakemake profile

BigJobMem: 250000     # Memory for MMSeqs in megabytes (e.g 64GB = 64000, recommend >= 64000)
BigJobCpu: 32        # Threads for MMSeqs (recommend >= 16)
BigJobTimeMin: 2000  # Max runtime in minutes  (this is only enforced by the Snakemake profile)
MediumJobMem: 32000  
MediumJobCpu: 16     
MediumJobTimeMin: 500
SmallJobMem: 16000   
SmallJobCpu: 8       
SmallJobTimeMin: 5

# DBs
kraken_db: 'blah'
kraken_db: 'blah'



