# Snakemake config
input:
output: 'tcga_cptac_taxonomic_profiler.out/'
log: 'tcga_cptac_taxonomic_profiler/tcga_cptac_taxonomic_profiler.log'

### STICK TO YOUR SYSTEM'S CPU:RAM RATIO FOR THESE
# this will be overwritten by the Snakemake profile

BigJobMem: 250000     # Memory for MMSeqs in megabytes (e.g 64GB = 64000, recommend >= 64000)
BigJobCpu: 32        # Threads for MMSeqs (recommend >= 16)
BigJobTimeMin: 2000  # Max runtime in minutes  (this is only enforced by the Snakemake profile)
MediumJobMem: 32000  
MediumJobCpu: 16     
SmallJobMem: 16000   
SmallJobCpu: 8       

# DBs
kraken_db: 'blah'
kraken_db: 'blah'

